<a href="https://colab.research.google.com/github/NAVEENKUMAR097/NAVEENKUMAR097/blob/main/Copy_of_DataPreprocessing_Assignment11_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Data.csv

**Step 1: Importing the libraries**

In [ ]:
import pandas as pd
import numpy as np



**Step 2: Importing dataset**

In [ ]:
data3 = pd.read_csv("Data.csv")
data3

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

**Step 3: Handling the missing data**

In [ ]:
data3.isna().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [ ]:
data3['Age'].fillna(data3['Age'].mean(),inplace=True)
data3['Salary'].fillna(data3['Salary'].mean(),inplace=True)
data3



Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

**Step 4: Encoding categorical data**

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
label = LabelEncoder()
onehot = OneHotEncoder()



array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

**Step 5: Creating a dummy variable**

In [ ]:
data3 = pd.get_dummies(data3,drop_first=True)
data3
x = data3.iloc[:,:-1]
y = data3.iloc[:,-1]



**Step 6: Splitting the datasets into training sets and Test sets**

In [ ]:
 from sklearn.model_selection import train_test_split
 x_train,x_test,y_train,y_test=train_test_split(x,y,test_size = 0.2)
 

**Step 7: Feature Scaling**

In [ ]:
from sklearn.preprocessing import StandardScaler
stand = StandardScaler()
x_train = stand.fit_transform(x_train)
x_test= stand.transform(x_test)
x_train,x_test



(array([[ 1.58235395,  1.67870079,  1.29099445, -0.57735027],
        [-0.43290816, -0.42992546, -0.77459667, -0.57735027],
        [ 0.23884588,  0.05740149,  1.29099445, -0.57735027],
        [-1.50771461, -1.27337597, -0.77459667,  1.73205081],
        [ 0.07463934, -0.93599577, -0.77459667,  1.73205081],
        [ 1.31365233,  1.34132059, -0.77459667, -0.57735027],
        [-0.16420654,  0.32917999, -0.77459667, -0.57735027],
        [-1.10466219, -0.76730567,  1.29099445, -0.57735027]]),
 array([[-0.02985573, -0.17689031, -0.77459667,  1.73205081],
        [ 0.77624911,  0.75090524, -0.77459667, -0.57735027]]))